var GetAllCategoriesResponseBody_8cs =
[
    [ "NookpostBackend.ApiSchemas.Categories.GetAllCategories.GetAllCategoriesResponseBody", "de/dd5/classNookpostBackend_1_1ApiSchemas_1_1Categories_1_1GetAllCategories_1_1GetAllCategoriesResponseBody.html", "de/dd5/classNookpostBackend_1_1ApiSchemas_1_1Categories_1_1GetAllCategories_1_1GetAllCategoriesResponseBody" ]
];